#torchrun --nproc_per_node=8 -m train --config_path configs/t3/distil_t3_dec.yml
model:
  model_id: dcae
  sample_size: [448,736]
  channels: 4
  latent_size: 8
  latent_channels: 128

  encoder_blocks_per_stage: [1, 1, 1, 1, 1]
  decoder_blocks_per_stage: [1, 1, 1, 1, 1]
  use_middle_block: false

  ch_0: 256
  ch_max: 2048

train:
  trainer_id: distill_dec
  data_id: t3_live_merge_4channel
  data_kwargs:
    root: "t3_data/"
    pose_root: "t3_pose/"
    target_size: [448, 736]
    pose_suffix: "_two_player_poses.npz"
    #bucket_name: cod-raw-360p
    #prefix: depth-and-raw

  use_torch_compile: false
  target_batch_size: 128
  batch_size: 16

  epochs: 200

  opt: AdamW
  opt_kwargs:
    lr: 2.0e-4
    weight_decay: 1.0e-4
    betas: [0.9, 0.95]
    eps: 1.0e-15

  lpips_type: convnext
  loss_weights:
    l2: 1.0
    lpips: 12.0
    gan: 0.0
    feature_matching: 0.0

  scheduler: LinearWarmup
  scheduler_kwargs:
    warmup_steps: 1500
    min_lr: 1.5e-5

  checkpoint_dir: checkpoints/t3_distill_dec_v1
  resume_ckpt: null

  sample_interval: 20
  save_interval: 2000

  teacher_cfg: configs/t3/tekken_H200_optimized.yml
  teacher_ckpt: checkpoints/tekken_vae_H200_v6/step_68000.pt

  latent_scale: 1.0

wandb:
  name: ${env:praymesh}
  project: t3VAE
  run_name: t3_distill_dec_v1